
services:
    development:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/var/www/html:delegated
        ports:
            - "8080:80"